### ISSUE TITLE
Offset is out of bounds at FSReqWrap.oncomplete (fs.js:82:15)

### ISSUE THREAD

**Issue by jleal52** [mafintosh/torrent-stream#153]
I've detected torrent with zero length files, give this error.

Running just this code:

```
var torrentStream = require('torrent-stream');
var parseTorrent = require('parse-torrent');

var parsed = parseTorrent('magnet:?xt=urn:btih:1eb72598ea9168f3e939b0f1e0b48b52e8613c03');
var engine = torrentStream(parsed);
engine.on('ready',function(e) {
        console.log('ready');
});
```

The stack trace error is:
```
fs.js:582
  binding.read(fd, buffer, offset, length, position, req);
          ^

Error: Offset is out of bounds
    at Error (native)
    at Object.fs.read (fs.js:582:11)
    at /home/usuario/torrent-coder/node_modules/torrent-stream/node_modules/random-access-file/index.js:77:6
    at apply (/home/usuario/torrent-coder/node_modules/torrent-stream/node_modules/thunky/index.js:16:28)
    at /home/usuario/torrent-coder/node_modules/torrent-stream/node_modules/thunky/index.js:20:25
    at onfinish (/home/usuario/torrent-coder/node_modules/torrent-stream/node_modules/random-access-file/index.js:37:4)
    at /home/usuario/torrent-coder/node_modules/torrent-stream/node_modules/random-access-file/index.js:43:49
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by jleal52** [comment]
Closed here: https://github.com/feross/webtorrent/issues/461
